app_student_type:
    resource: "@AppBundle/Controller/StudentTypeController.php"
    type:     annotation

bunker:
    resource: "@BunkerBundle/Controller/"
    type:     annotation
    prefix:   /

hetic:
    resource: "@HeticBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
